### ISSUE TITLE
Split databases compatibility

### ISSUE THREAD

**Issue by tdgroot** [elgentos/masquerade#23]
Haven't tried it yet, but I was wondering if it's possible to run on separate dumps from a split database environment? 
There would be 3 dumps:
- default
- checkout (quotes)
- sales

In other words, does it rely on all the usual tables being present?

**Comment by peterjaap** [comment]
We've defined groups so you can add the --group flag to only anon the sales tables for instance. Not sure whether the current splitting in groups matches up with how Magento Commerce splits the databases though.

**Comment by tdgroot** [comment]
Thanks, I'll see how it works coming weeks.

**Comment by tdgroot** [comment]
It seems to work fine, it just skips the table if it doesn't exists!
