### ISSUE TITLE
Unique customer email addresses not so unique

### ISSUE THREAD

**Issue by tdgroot** [elgentos/masquerade#25]
Sorry for all the issuing lately.

I'm getting the following error when anonymizing the customer_entity table:
```
Updating customer_entity
   6480/107551 [=>--------------------------]   6%
In Connection.php line 664:
                                                                                                                                     
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'rpaucek@yahoo.com-2' for key 'CUSTOMER_ENTITY_EMAIL_WEBSIT  
  E_ID' (SQL: update `customer_entity` set `email` = rpaucek@yahoo.com, `prefix` = , `firstname` = Ramon, `middlename` = , `lastnam  
  e` = Rice, `suffix` =  where `entity_id` = 6515)
```

Even though `email` is set to unique, faker sometimes generates email addresses which have already been used in the same runtime. This probably happens because faker only has so many data that recurrence might happen.

Here are some ideas to fix this issue:
- Regenerate the value if it's already been used in current runtime (up to x times)
- Write own [Internet formatter](https://github.com/fzaninotto/Faker/blob/master/src/Faker/Provider/Internet.php#L16)
- Add customer entity_id to email address

**Comment by peterjaap** [comment]
If Faker does not have enough data points to support all 107551 customer entries in your table, why would it then already encounter this error at 6480? I've done runs with more customers than that and had no issues.

Is this perhaps your second run on the same table?

**Comment by peterjaap** [comment]
Hmm no that shouldn't happen due to nulling the values before every run; https://github.com/elgentos/masquerade/blob/master/src/config/magento2/customer.yaml#L7

**Comment by tdgroot** [comment]
I'll try it again with a fresh database when I find the time coming week, just to be sure that isn't the case.
