### ISSUE TITLE
Installation not working with last release (0.1.10)

### ISSUE THREAD

**Issue by jeromecx** [elgentos/masquerade#37]
Hello and thank you for sharing the code,

I've tried to install Masquerade by following the instructions described in README.md (line 61) : 

```
wget https://github.com/elgentos/masquerade/releases/download/0.1.10/masquerade.phar
```
and i received a 404 error.

However, it works with release v 0.1.9

Best regards

**Comment by peterjaap** [comment]
Thanks for noticing, I've built and uploaded the phar file to the release.

**Comment by jeromecx** [comment]
thank you @peterjaap
