### ISSUE TITLE
Add a wiki page for Bitbucket Pipelines usage

### ISSUE THREAD

**Issue by johnorourke** [elgentos/masquerade#52]
I wrote up our Bitbucket usage here: https://github.com/getjohn/masquerade/wiki/Bitbucket-Pipelines-Usage

Feel free to add it to your wiki :)

**Comment by peterjaap** [comment]
Thanks, I've added it! https://github.com/elgentos/masquerade/wiki/Usage-with-Bitbucket-Pipelines
