### ISSUE TITLE
I think the latest release might be broken?

### ISSUE THREAD

**Issue by mikemountjoy99** [elgentos/masquerade#56]
**0.1.13**
wget https://github.com/elgentos/masquerade/releases/download/0.1.13/masquerade.phar

returns 647bytes

**0.1.12**
wget https://github.com/elgentos/masquerade/releases/download/0.1.12/masquerade.phar

returns 3.2MB

This is a terrific tool BTW 🥇

**Comment by peterjaap** [comment]
Yes you're right, thanks for catching that! Will fix asap

**Comment by peterjaap** [comment]
Woops, I grabbed the masquerade file from the bin dir instead of the dist dir!

**Comment by peterjaap** [comment]
I guess that's why we need #27  :P

**Comment by peterjaap** [comment]
New release with correct phar file; https://github.com/elgentos/masquerade/releases/tag/0.2.0
