### ISSUE TITLE
Error after install

### ISSUE THREAD

**Issue by deedy-tech** [elgentos/masquerade#59]
Hi
I have followed the installation instructions and "Download the phar file:

curl -L -o masquerade.phar https://github.com/elgentos/masquerade/releases/latest/download/masquerade.phar
"

When I then run 

php masquerade.phar run --help

I get the error 

`PHP Warning:  require(phar:///home/ubuntu/masquerade.phar/vendor/composer/../symfony/translation/Resources/functions.php): failed to open stream: phar error: "vendor/symfony/translation/Resources/functions.php" is not a file in phar "/home/ubuntu/masquerade.phar" in phar:///home/ubuntu/masquerade.phar/vendor/composer/autoload_real.php on line 69
PHP Fatal error:  require(): Failed opening required 'phar:///home/ubuntu/masquerade.phar/vendor/composer/../symfony/translation/Resources/functions.php' (include_path='.:/usr/share/php') in phar:///home/ubuntu/masquerade.phar/vendor/composer/autoload_real.php on line 69`

Am I missing a step?

I am trying to run it on Ubuntu 20.04 with php 7.3.26

Thanks
Rob

**Comment by peterjaap** [comment]
Huh you're right. For now, try this version; https://github.com/elgentos/masquerade/releases/download/0.1.12/masquerade.phar

**Comment by deedy-tech** [comment]
Hi Peter
Thanks for looking at the issue.

I actually found that link to version 0.1.12 by looking at an earlier issue
and I have it installed and kind of got it working.

I am using it on a Magento 2 platform and if I create the  config file

config/magento2/admin.yaml

and put "admin:" in it (as per instructions), when I run Masquerade, I get

._ _  _. _ _.    _ .__. _| _
| | |(_|_>(_||_|(/_|(_|(_|(/_
            |
                   by elgentos
                        v0.1.12
PHP Warning:  Invalid argument supplied for foreach() in
phar:///opt/masquerade/masquerade.phar/src/Elgentos/Masquerade/Console/RunCommand.php
on line 110

Updating sales_creditmemo
    0 [>---------------------------]




I then tried putting

admin:
  admin_user:
    provider: # this sets options specific to the type of table
    where: "`email` not like '%@example.com' OR email not like '%@moo.com'"


and get the error

_ _  _. _ _.    _ .__. _| _
| | |(_|_>(_||_|(/_|(_|(_|(/_
            |
                   by elgentos
                        v0.1.12
PHP Notice:  Undefined index: columns in
phar:///opt/masquerade/masquerade.phar/src/Elgentos/Masquerade/Console/RunCommand.php
on line 129
PHP Warning:  Invalid argument supplied for foreach() in
phar:///opt/masquerade/masquerade.phar/src/Elgentos/Masquerade/Console/RunCommand.php
on line 129

Updating admin_user
  0/12 [>---------------------------]   0%PHP Notice:  Undefined index:
columns in
phar:///opt/masquerade/masquerade.phar/src/Elgentos/Masquerade/Console/RunCommand.php
on line 147
PHP Warning:  Invalid argument supplied for foreach() in
phar:///opt/masquerade/masquerade.phar/src/Elgentos/Masquerade/Console/RunCommand.php
on line 147

In Connection.php line 664:



  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'entity_id' in
'order clause' (SQL: select * from `admin_user` order by `entity_id` asc
limit 100 offset 0)




In PDOConnection.php line 63:


  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'entity_id' in
'order clause'



In PDOConnection.php line 61:


  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'entity_id' in
'order clause'



run [--platform [PLATFORM]] [--driver [DRIVER]] [--database [DATABASE]]
[--username [USERNAME]] [--password [PASSWORD]] [--host [HOST]] [--prefix
[PREFIX]] [--locale [LOCALE]] [--group [GROUP]] [--charset [CHARSET]]


Cheers


Rob Gilchrist
t: 07747633261
e: rob@deedy.tech [image: Deedy-Technology-Wide-Logo]

**Comment by peterjaap** [comment]
@deedy-tech are you on Magento Commerce? I believe that uses `row_id` instead of `entity_id`, hadn't thought of that (we never use Commerce).

**Comment by deedy-tech** [comment]
Hi 
No, I am currently using Magento CE vs 2.3.3. 

For the admin_user table the primary key is user_id. 

I tried setting the admin.yaml file to 
admin:
  admin_user:
    provider: # this sets options specific to the type of table
    where: "email not like '%@moo.com' OR email not like '%@moo.co.uk'"
    pk: user_id

but got the following

`PHP Notice:  Undefined index: columns in phar:///opt/masquerade/masquerade.phar/src/Elgentos/Masquerade/Console/RunCommand.php on line 129
PHP Warning:  Invalid argument supplied for foreach() in phar:///opt/masquerade/masquerade.phar/src/Elgentos/Masquerade/Console/RunCommand.php on line 129

Updating admin_user
  0/12 [>---------------------------]   0%PHP Notice:  Undefined index: columns in phar:///opt/masquerade/masquerade.phar/src/Elgentos/Masquerade/Console/RunCommand.php on line 147
PHP Warning:  Invalid argument supplied for foreach() in phar:///opt/masquerade/masquerade.phar/src/Elgentos/Masquerade/Console/RunCommand.php on line 147
PHP Notice:  Undefined index: columns in phar:///opt/masquerade/masquerade.phar/src/Elgentos/Masquerade/Console/RunCommand.php on line 156
PHP Warning:  Invalid argument supplied for foreach() in phar:///opt/masquerade/masquerade.phar/src/Elgentos/Masquerade/Console/RunCommand.php on line 156

In Connection.php line 664:
                                                                                                                                                                            
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the rig  
  ht syntax to use near 'where `user_id` = ?' at line 1 (SQL: update `admin_user` set  where `user_id` = 1)                                                                 
                                                                                                                                                                            

In PDOConnection.php line 63:
                                                                                                                                                                            
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the rig  
  ht syntax to use near 'where `user_id` = ?' at line 1                                                                                                                     
                                                                                                                                                                            

In PDOConnection.php line 61:
                                                                                                                                                                            
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the rig  
  ht syntax to use near 'where `user_id` = ?' at line 1                                                                                                                     
                                                                                                                                                                            

run [--platform [PLATFORM]] [--driver [DRIVER]] [--database [DATABASE]] [--username [USERNAME]] [--password [PASSWORD]] [--host [HOST]] [--prefix [PREFIX]] [--locale [LOCALE]] [--group [GROUP]] [--charset [CHARSET]]`

**Comment by peterjaap** [comment]
The `where` option has been introduced in version 0.2.0 so the version you're using does not support it.

**Comment by deedy-tech** [comment]
Ah, thanks for letting me know.

**Comment by enriquetarazona** [comment]
I´m having same issue trying to run the latest release version. Any update on this? 
 
Thanks

**Comment by peterjaap** [comment]
Thanks for your reports, I fixed it. You can download 0.2.1 here;

https://github.com/elgentos/masquerade/releases/download/0.2.1/masquerade.phar
