### ISSUE TITLE
Skip if table does not exist

### ISSUE THREAD

**Issue by uznog** [elgentos/masquerade#61]
Hello,

is skipping not existing tables possible? I can see #11 resolved non-existing columns issue, but it would be great not to fail when the specific table isn't present (i.e. with a cmd flag switch?)

**Comment by peterjaap** [comment]
Should be, see https://github.com/elgentos/masquerade#customization

**Comment by uznog** [comment]
That's correct, although it will just skip the table. What I'd like to achieve is to have table's anonymization configured in yaml, but used when table exists and skipped otherwise. It would be nice to have one set of configs with any possible tables for anonymization process, as some clients use different modules - schemas differ between various clients' databases.

**Comment by peterjaap** [comment]
Ok I'm open to PR's :)

**Comment by peterjaap** [comment]
Done in 0.2.4 :)

**Comment by peterjaap** [comment]
Also see #65, I'd love to hear your thoughts on this.
