### ISSUE TITLE
download of masquerade.phar broken after 0.3.5 releae

### ISSUE THREAD

**Issue by bad** [elgentos/masquerade#87]
Thanks for the quick release yesterday.

Alas, downloading https://github.com/elgentos/masquerade/releases/latest/download/masquerade.phar
no longer works.

Actually, it would be nice if one could download the phar for a tagged release.  E.g. https://github.com/elgentos/masquerade/releases/0.3.5/download/masquerade.phar or something like that.

**Comment by peterjaap** [comment]
@bad thanks for notifying, apparently I clicked submit too quick yesterday.

The latest link you posted works again.

There are downloads per tagged release, this is the latest one; https://github.com/elgentos/masquerade/releases/download/0.3.5/masquerade.phar

**Comment by bad** [comment]
On Thu, Sep 23, 2021 at 01:36:50AM -0700, Peter Jaap Blaakmeer wrote:
> There are downloads per tagged release, this is the latest one; https://github.com/elgentos/masquerade/releases/download/0.3.5/masquerade.phar

Ah, I see.  masquerade.phar is missing in the assets for the 0.3.4 release
and I forgot to expand the assets for the earlier releases.

No worries.
--chris
