### ISSUE TITLE
Unable to use with Magento 2.4.4 (latest)

### ISSUE THREAD

**Issue by davidwindell** [elgentos/masquerade#96]
magento/magento2-base 2.4.4 requires symfony/console ~4.4.0

**Comment by peterjaap** [comment]
You could always use the binary in the meantime :)

**Comment by davidwindell** [comment]
Good point, I hadn't considered not installing with composer :+1:

**Comment by davidwindell** [comment]
@peterjaap looks like it works, but there are a number of PHP 8.1 deprecated errors, like:

```
PHP Deprecated:  Return type of HumbugBox3100\KevinGH\RequirementChecker\RequirementCollection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///workspace/project/masquerade.phar/.box/src/RequirementCollection.php on line 15
```
etc, etc

Is that expected?

**Comment by peterjaap** [comment]
Apparently Box needs to updated, so it includes this MR https://github.com/box-project/box/pull/587

**Comment by peterjaap** [comment]
@davidwindell could you test this build?

[masquerade.zip](https://github.com/elgentos/masquerade/files/9064423/masquerade.zip)

**Comment by davidwindell** [comment]
@peterjaap thanks, that removes some of the errors, I've just tested the `identify` command and get:

```
Deprecated: preg_replace(): Passing null to parameter #2 ($replacement) of type array|string is deprecated in phar:///workspace/project/masquerade.phar/src/Elgentos/Masquerade/Console/IdentifyCommand.php on line 296
PHP Deprecated:  preg_replace(): Passing null to parameter #2 ($replacement) of type array|string is deprecated in phar:///workspace/project/masquerade.phar/src/Elgentos/Masquerade/Console/IdentifyCommand.php on line 296****
```

**Comment by peterjaap** [comment]
@davidwindell and this one?

[masquerade.zip](https://github.com/elgentos/masquerade/files/9066304/masquerade.zip)

**Comment by davidwindell** [comment]
@peterjaap that seems pretty good to me, I've only tested the identify command but there aren't any errors on that one now :1st_place_medal:

**Comment by peterjaap** [comment]
Thanks for testing @davidwindell , I've issued a new release https://github.com/elgentos/masquerade/releases/tag/1.2.0
